spin_manifest_version = 2

[application]
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = "Example of handling post data"
name = "ts-router-post"
version = "0.1.0"

[[trigger.http]]
route = "/example/..."
component = "ts-router-post"

[component.ts-router-post]
source = "target/ts-router-post.wasm"
exclude_files = ["**/node_modules"]
[component.ts-router-post.build]
command = "npm run build"
